In [65]:
import pandas as pd

data = pd.read_csv('C:\\Users\\krist\\Documents\\Uni\\RWTH\\WS23\\Master_project\\Data\\combined_DE_politician_twitter_timelines_2016-01-01_to_2023-02-11_clean.txt', sep = ",")
mdbs = pd.read_csv('C:\\Users\\krist\\Documents\\Uni\\RWTH\\WS23\\Master_project\\Data\\DE_politician_twitter_users.csv')

In [66]:
mdbs['author_id'].head()

0    1419751204465356805
1    1416388709264633858
2    1413536612068245507
3    1411676203224870912
4    1410671503679574016
Name: author_id, dtype: int64

In [63]:
data.head()

,id,author_id,created_at,expanded_urls,retweeted,quoted,reply,text,retweet_count,reply_count,like_count,quote_count
0,1623371262864068617,1419751204465356805,2023-02-08 17:20:44+00:00,[],False,False,False,"Shell, ExxonMobil, Total Energies, sie alle ha...",10,8,70,0
1,1622589284002717700,1419751204465356805,2023-02-06 13:33:26+00:00,['https://twitter.com/FBsirske/status/16225892...,False,False,False,"Die Post streikt!\n\nDie Post macht 8,4 Millia...",12,5,111,0
2,1621139288103735297,1419751204465356805,2023-02-02 13:31:40+00:00,['https://twitter.com/kimvsparrentak/status/16...,False,True,False,Uber und Co. hintergehen geltendes Arbeitsrech...,5,2,15,0
3,1620521818292617217,1419751204465356805,2023-01-31 20:38:03+00:00,[],False,False,False,"Die Überlegungen aus der FDP, wegen des #Soli ...",4,9,52,0
4,1620357371506884610,1419751204465356805,2023-01-31 09:44:36+00:00,['https://www.tagesschau.de/eilmeldung/solidar...,False,False,False,Spitzenverdiener zur Kasse! \n\nDer #Soli nütz...,3,0,14,0

In [67]:
replace = {}
for index,row in mdbs.iterrows():
    replace[row['author_id']] = row['name']

In [93]:
data_with_authors = data.copy()
data_with_authors['name'] = data_with_authors['author_id'].copy()
data_with_authors.replace(to_replace={"name":replace},inplace=True)

In [94]:
data_with_authors.head()

,id,author_id,created_at,expanded_urls,retweeted,quoted,reply,text,retweet_count,reply_count,like_count,quote_count,name
0,1623371262864068617,1419751204465356805,2023-02-08 17:20:44+00:00,[],False,False,False,"Shell, ExxonMobil, Total Energies, sie alle ha...",10,8,70,0,Frank Bsirske
1,1622589284002717700,1419751204465356805,2023-02-06 13:33:26+00:00,['https://twitter.com/FBsirske/status/16225892...,False,False,False,"Die Post streikt!\n\nDie Post macht 8,4 Millia...",12,5,111,0,Frank Bsirske
2,1621139288103735297,1419751204465356805,2023-02-02 13:31:40+00:00,['https://twitter.com/kimvsparrentak/status/16...,False,True,False,Uber und Co. hintergehen geltendes Arbeitsrech...,5,2,15,0,Frank Bsirske
3,1620521818292617217,1419751204465356805,2023-01-31 20:38:03+00:00,[],False,False,False,"Die Überlegungen aus der FDP, wegen des #Soli ...",4,9,52,0,Frank Bsirske
4,1620357371506884610,1419751204465356805,2023-01-31 09:44:36+00:00,['https://www.tagesschau.de/eilmeldung/solidar...,False,False,False,Spitzenverdiener zur Kasse! \n\nDer #Soli nütz...,3,0,14,0,Frank Bsirske

In [95]:
replace_party = {}
for index,row in mdbs.iterrows():
    replace_party[row['author_id']] = row['party']

data_with_authors['party'] = data_with_authors['author_id'].copy()
data_with_authors = data_with_authors.replace(to_replace={'party':replace_party})

In [96]:
data_with_authors.head()

,id,author_id,created_at,expanded_urls,retweeted,quoted,reply,text,retweet_count,reply_count,like_count,quote_count,name,party
0,1623371262864068617,1419751204465356805,2023-02-08 17:20:44+00:00,[],False,False,False,"Shell, ExxonMobil, Total Energies, sie alle ha...",10,8,70,0,Frank Bsirske,Alliance 90/The Greens
1,1622589284002717700,1419751204465356805,2023-02-06 13:33:26+00:00,['https://twitter.com/FBsirske/status/16225892...,False,False,False,"Die Post streikt!\n\nDie Post macht 8,4 Millia...",12,5,111,0,Frank Bsirske,Alliance 90/The Greens
2,1621139288103735297,1419751204465356805,2023-02-02 13:31:40+00:00,['https://twitter.com/kimvsparrentak/status/16...,False,True,False,Uber und Co. hintergehen geltendes Arbeitsrech...,5,2,15,0,Frank Bsirske,Alliance 90/The Greens
3,1620521818292617217,1419751204465356805,2023-01-31 20:38:03+00:00,[],False,False,False,"Die Überlegungen aus der FDP, wegen des #Soli ...",4,9,52,0,Frank Bsirske,Alliance 90/The Greens
4,1620357371506884610,1419751204465356805,2023-01-31 09:44:36+00:00,['https://www.tagesschau.de/eilmeldung/solidar...,False,False,False,Spitzenverdiener zur Kasse! \n\nDer #Soli nütz...,3,0,14,0,Frank Bsirske,Alliance 90/The Greens

In [97]:
data_with_authors.to_csv('C:\\Users\\krist\\Documents\\Uni\\RWTH\\WS23\\Master_project\\Data\\tweets_with_name_party.csv')